= REST Cards

:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs

[[Overview]]
Сервис предназначен для работы с объектом Карты.

*Параметры объекта*
|===
| Параметр | Тип | Описание

| id
| String
| ID карты

| direction
| String
| Карта списания или зачисления ('sender' - карты, с которых переводили, 'recipient' - карты, на которые переводили)

| color
| String
| Код цвета карты

| name
| String
| Название карты

| verification 
| String
| Статус верификации карты (S - 3DS, H - hold, N - not verify)

| active
| String
| Активная карта? (true/false)

| alfabank
| String
| Карта Альфа-Банка? (true/false)

| number
| String
| Номер карты

| expirationYear
| Integer
| Год окончания срока действия карты

| expirationMonth
| Integer
| Месяц окончания срока действия карты

| lastTransactionDateForSender
| Date
| Дата последнего перевода с карты

| lastTransactionDateForRecipient
| Date
| Дата последнего перевода на карту

| paymentSystem
| String
| Платежная система

3+ | Account

| Balance
| Integer
| Account balance

3+ | Currency

| Code
| String
| Код валюты

| Description
| String
| Название валюты

3+ | Bank

| Id
| String
| ID банка

| latinName
| String
| Латинское название банка

| сyrillicName 
| String
| Кириллическое название банка

| countryCode
| String
| Код страны

| Color
| String
| Цвет банка
|===

*Пример объекта*
----
{
  "id": "1",
  "color": "#000002",
  "name": null,
  "direction": "sender",
  "verification": "S",
  "active": true,
  "alfabank": false,
  "number": "5154 **** 4025",
  "expirationYear": "15",
  "expirationMonth": "07",
  "lastTransactionDateForSender": "2015-12-15",
  "lastTransactionDateForRecipient": "2015-01-15",
  "paymentSystem": "MC",
  "Accoun"
  {
  }
  "accountBalance": "15250.50",
  "accountCurrency": "USD",
  "accountCurrenceName": "Доллар США",
  "bankId": "12345679",
  "bankNameLatin": "Sberbank",
  "bankNameCyrillic": "Сбербанк",
  "countryCode": "12",
  "bankColor": "#000008",
}
----

[[overview-http-verbs]]
== Список методов

|===
| Метод | Описание

| `GET /cards`
| Получение списка карт клиента с параметрами

| `GET /cards/123`
| Получение параметров заданной карты

| `POST /cards`
| Сохранение новой карты в системе

| `PATCH /cards/123`
| Редактирование параметров карты в системе


|===

[[Errors]]
== Ошибки

пока хз
 
|===
| Поле | писание

| error
| ''

| message
| ''

| path
| ''

| status
| ''

| timestamp
| ''
|===


[[resources-card]]
== Карты

[[resources-card-access]]
=== Метод GET

* Получение списка карт в поле отправителя перевода

==== Пример запроса

*GET* /cards?cus=AQHFFT&cardVerification=S&isDeleted=N&mode=A&direction=SND

==== Примеры ответа

----
{
}

[
  {
  "humanId": "12345",
  "cardId": "0",
  "cardColor": "#000001",
  "cardName": "Вася Пупкин",
  "isSending": "Y",
  "isReception": "N",
  "cardVerification": "S",
  "isDeletedDebit": "N",
  "isActive": "Y",
  "isAlfabank": "Y",
  "cardNumber": "5154 **** 4025",
  "expirationDate": "07/15",
  "isDeletedCredit": "N",
  "lastTransactionDateForSender": "2015-12-15",
  "lastTransactionDateForRecipient": "2015-01-15",
  "paymentSystem": "MC",
  "accountBalance": "15250.50",
  "accountCurrency": "RUR",
  "accountCurrenceName": "Рубли",
  "bankId": "12345678",
  "bankNameLatin": "Alfabank",
  "bankNameCyrillic": "Альфа-Банк",
  "countryCode": "12",
  "bankColor": "#000009",
  },
  {
  "humanId": "12345",
  "cardId": "1",
  "cardColor": "#000002",
  "cardName": "Вася Пупкин 2",
  "isSending": "Y",
  "isReception": "Y",
  "cardVerification": "S",
  "isDeletedDebit": "N",
  "isActive": "Y",
  "isAlfabank": "Y",
  "cardNumber": "5154 **** 4025",
  "expirationDate": "07/15",
  "isDeletedCredit": "N",
  "lastTransactionDateForSender": "2015-12-15",
  "lastTransactionDateForRecipient": "2015-01-15",
  "paymentSystem": "MC",
  "accountBalance": "15250.50",
  "accountCurrency": "RUR",
  "accountCurrenceName": "Рубли",
  "bankId": "12345678",
  "bankNameLatin": "Alfabank",
  "bankNameCyrillic": "Альфа-Банк",
  "countryCode": "12",
  "bankColor": "#000009",
  }
]
----

* Получение списка карт в поле получателя перевода

==== Пример запроса

*GET* /cards?cus=AQHFFT&cardVerification=S&isDeleted=N&mode=A&direction=RCP

==== Примеры ответа

----
{
  "type":"List",
  "value":[
    {
    "humanId":""12345,
    "cardId":"1",
    "cardColor":"#000002",
    "cardName":"",
    "isSending":"Y",
    "isReception":"Y",
    "cardVerification":"S",
    "isDeletedDebit":"N",
    "isActive":"Y",
    "isAlfabank":"N",
    "cardNumber":"5154 **** 4025",
    "expirationDate":"07/15",
    "isDeletedCredit":"N",
    "lastTransactionDateForSender":"2015-12-15",
    "lastTransactionDateForRecipient":"2015-01-15",
    "paymentSystem":"MC",
    "accountBalance":"15250.50",
    "accountCurrency":"USD",
    "accountCurrenceName":"Доллар США",
    "bankId":"12345679",
    "bankNameLatin":"Sberbank",
    "bankNameCyrillic":"Сбербанк",
    "countryCode":"12",
    "bankColor":"#000008",
    }
  ]
}
----

* Получение параметров заданной карты

==== Пример запроса

*GET* /cards?id=1

==== Примеры ответа

----
{
  "humanId":""12345,
  "cardId":"1",
  "cardColor":"#000002",
  "cardName":"",
  "isSending":"Y",
  "isReception":"Y",
  "cardVerification":"S",
  "isDeletedDebit":"N",
  "isActive":"Y",
  "isAlfabank":"N",
  "cardNumber":"5154 **** 4025",
  "expirationDate":"07/15",
  "isDeletedCredit":"N",
  "lastTransactionDateForSender":"2015-12-15",
  "lastTransactionDateForRecipient":"2015-01-15",
  "paymentSystem":"MC",
  "accountBalance":"15250.50",
  "accountCurrency":"USD",
  "accountCurrenceName":"Доллар США",
  "bankId":"12345679",
  "bankNameLatin":"Sberbank",
  "bankNameCyrillic":"Сбербанк",
  "countryCode":"12",
  "bankColor":"#000008",
}
----

[[resources-card-create]]
=== Метод PUT

* Сохранение новой карты после совершения перевода

==== Пример запроса

*PUT* /cards/?id=1

==== Примеры ответа

----
{
  "Id": "1",
  "Color": "#000002",
  "Name": null,
  "isSending":"Y",
  "isReception":"Y",
  "cardVerification":"S",
  "isDeletedDebit":"N",
  "isActive":"Y",
  "isAlfabank":"N",
  "cardNumber":"5154 **** 4025",
  "expirationDate":"07/15",
  "isDeletedCredit":"N",
  "lastTransactionDateForSender":"2015-12-15",
  "lastTransactionDateForRecipient":"2015-01-15",
  "paymentSystem":"MC",
  "accountBalance":"15250.50",
  "accountCurrency":"USD",
  "accountCurrenceName":"Доллар США",
  "bankId":"12345679",
  "bankNameLatin":"Sberbank",
  "bankNameCyrillic":"Сбербанк",
  "countryCode":"12",
  "bankColor":"#000008",
}
----

[[resources-card-update]]
=== Метод POST

* Сохранение даты последнего перевода

* Сохранение названия карты
