= REST CardList

:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs

[[Overview]]
Сервис предназначен для работы с объектом Карты

[[overview-http-verbs]]
== Список методов

|===
| Метод | Описание

| `GET /cards`
| Получение списка карт клиента с параметрами

| `PUT /cards`
| Сохранение новой карты в системе

| `POST /cards/{id}`
| Редактирование параметров карты в системе


|===

[[Errors]]
== Ошибки

 хз
 
|===
| Поле | писание

| error
| ``

| message
| ''

| path
| ''

| status
| ``

| timestamp
| '...'
|===


[[resources-card]]
== Карты

[[resources-card-access]]
=== Метод GET

* Получение списка карт в поле отправителя платежа

==== Пример запроса

get /cards/?cus=AQHFFT&cardVerification=S&isDeleted=N&mode=A&direction=SND

==== Примеры ответа

----
{
  "type":"List",
  "value":[
    {
    "humanId":"12345",
    "cardId":"0",
    "cardColor":"#000001",
    "cardName":"Вася Пупкин",
    "isSending":"Y",
    "isReception":"N",
    "cardVerification":"S",
    isDefaultDebit
    isDeletedDebit
    isActive
    "isAlfabank":"Y",
    "cardNumber":"4154 **** 4025",
    "expirationDate":"07/15",
    applicationId
    isDefaultCredit
    isDeletedCredit
    "lastTransactionDateForSender":"",
    "lastTransactionDateForRecipient":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "paySys":"VI",
    "name":"",
    "debit":true,
    "credit":false,
    "verificationMethod":"3DS",
    "isActive":true,
    "isDefault":true,
    "isAlfaCard":true,
    "number":"4154 82** **** **40 25",
    "expirationDate":"07/15"
    "balance":"15000.15",
    "bankId":"AlfaBank"
    "bankColor":"#000001",
    },
    {
    "cardId":"1",
    "paySys":"MC",
    "name":"name2",
    "debit":true,
    "credit":false,
    "verificationMethod":"3DS",
    "isActive":true,
    "isDefault":false,
    "isAlfaCard":false,
    "number":"5154 82** **** **40 25",
    "expirationDate":"07/15"
    "bank":{
      "logo":"logo2",
      "color":"green"
      }
    }
  ]
}
----

* Получение списка карт в поле получателя перевода

==== Пример запроса

get /cards/?credit=true

==== Примеры ответа

----
{
  "type":"List",
  "value":[
    {
    "cardId":"3",
    "paySys":"VISA",
    "name":"name3",
    "debit":false,
    "credit":true",
    "verificationMethod":"3DS",
    "isActive":true,
    "isDefault":true,
    "isAlfaCard":true,
    "number":"4154 82** **** **40 25",
    "expirationDate":"07/15"
    "bank":{
      "logo":"logo1",
      "color":"blue"
      }
    }
  ]
}
----

[[resources-card-create]]
=== Метод PUT

==== Пример запроса

PUT /cards/?cus=AHQFFT

==== Пример ответа

[[resources-card-update]]
=== Метод POST

* Сохранение даты последнего перевода

* Сохранение названия карты
