= REST Cards

:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs

[[Overview]]
Сервис предназначен для работы с объектом Карты.

*Параметры объекта*
|===
| Параметр | Тип | Описание

| humanId
| String
| Human ID

| cardId
| String
| Card ID

| cardColor
| String
| Card color

| cardName
| String
| Card name

| isSending
| String
| Is sending card? (Y/N)

| isReception
| String
| Is reception card? (Y/N)

| cardVerification 
| String
| Card's verification ('S' - 3DS,'H' - hold,'N' - not verify)

| isDeletedDebit
| String
| Is deleted debit card? (Y/N)

| isActive
| String
| Is active card? (Y/N)

| isAlfabank
| String
| Is AlfaBank card and none of the merchants? (Y/N)

| cardNumber
| String
| Card number

| expirationYear
| Integer
| Card expriration year

| expirationMonth
| Integer
| Card expriration month

| isDeletedCredit
| String
| Is deleted credit card? (Y/N)

| lastTransactionDateForSender
| Date
| Last transaction date for sender card

| lastTransactionDateForRecipient
| Date
| Last transaction date for recipient card

| paymentSystem
| String
| Payment system

| accountBalance
| Integer
| Account balance

| accountCurrency
| String
| Account currency 

| accountCurrenceName
| String
| Account currency name

| bankId
| String
| Bank ID

| bankNameLatin 
| String
| Latin name of bank

| bankNameCyrillic 
| String
| Cyrillic name of bank

| countryCode
| String
| Country code

| bankColor
| String
| Bank color


*Пример объекта*
----
{
  "humanId": "12345",
  "cardId": "1",
  "cardColor": "#000002",
  "cardName": null,
  "isSending": "Y",
  "isReception": "Y",
  "cardVerification": "S",
  "isDeletedDebit": "N",
  "isActive": "Y",
  "isAlfabank": "N",
  "cardNumber": "5154 **** 4025",
  "expirationDate": "07/15",
  "isDeletedCredit": "N",
  "lastTransactionDateForSender": "2015-12-15",
  "lastTransactionDateForRecipient": "2015-01-15",
  "paymentSystem": "MC",
  "accountBalance": "15250.50",
  "accountCurrency": "USD",
  "accountCurrenceName": "Доллар США",
  "bankId": "12345679",
  "bankNameLatin": "Sberbank",
  "bankNameCyrillic": "Сбербанк",
  "countryCode": "12",
  "bankColor": "#000008",
}
----

[[overview-http-verbs]]
== Список методов

|===
| Метод | Описание

| `GET /cards`
| Получение списка карт клиента с параметрами

| `GET /cards/123`
| Получение параметров заданной карты

| `POST /cards`
| Сохранение новой карты в системе

| `PATCH /cards/123`
| Редактирование параметров карты в системе


|===

[[Errors]]
== Ошибки

пока хз
 
|===
| Поле | писание

| error
| ''

| message
| ''

| path
| ''

| status
| ''

| timestamp
| ''
|===


[[resources-card]]
== Карты

[[resources-card-access]]
=== Метод GET

* Получение списка карт в поле отправителя перевода

==== Пример запроса

*GET* /cards?cus=AQHFFT&cardVerification=S&isDeleted=N&mode=A&direction=SND

==== Примеры ответа

----
{
}

[
  {
  "humanId": "12345",
  "cardId": "0",
  "cardColor": "#000001",
  "cardName": "Вася Пупкин",
  "isSending": "Y",
  "isReception": "N",
  "cardVerification": "S",
  "isDeletedDebit": "N",
  "isActive": "Y",
  "isAlfabank": "Y",
  "cardNumber": "5154 **** 4025",
  "expirationDate": "07/15",
  "isDeletedCredit": "N",
  "lastTransactionDateForSender": "2015-12-15",
  "lastTransactionDateForRecipient": "2015-01-15",
  "paymentSystem": "MC",
  "accountBalance": "15250.50",
  "accountCurrency": "RUR",
  "accountCurrenceName": "Рубли",
  "bankId": "12345678",
  "bankNameLatin": "Alfabank",
  "bankNameCyrillic": "Альфа-Банк",
  "countryCode": "12",
  "bankColor": "#000009",
  },
  {
  "humanId": "12345",
  "cardId": "1",
  "cardColor": "#000002",
  "cardName": "Вася Пупкин 2",
  "isSending": "Y",
  "isReception": "Y",
  "cardVerification": "S",
  "isDeletedDebit": "N",
  "isActive": "Y",
  "isAlfabank": "Y",
  "cardNumber": "5154 **** 4025",
  "expirationDate": "07/15",
  "isDeletedCredit": "N",
  "lastTransactionDateForSender": "2015-12-15",
  "lastTransactionDateForRecipient": "2015-01-15",
  "paymentSystem": "MC",
  "accountBalance": "15250.50",
  "accountCurrency": "RUR",
  "accountCurrenceName": "Рубли",
  "bankId": "12345678",
  "bankNameLatin": "Alfabank",
  "bankNameCyrillic": "Альфа-Банк",
  "countryCode": "12",
  "bankColor": "#000009",
  }
]
----

* Получение списка карт в поле получателя перевода

==== Пример запроса

*GET* /cards?cus=AQHFFT&cardVerification=S&isDeleted=N&mode=A&direction=RCP

==== Примеры ответа

----
{
  "type":"List",
  "value":[
    {
    "humanId":""12345,
    "cardId":"1",
    "cardColor":"#000002",
    "cardName":"",
    "isSending":"Y",
    "isReception":"Y",
    "cardVerification":"S",
    "isDeletedDebit":"N",
    "isActive":"Y",
    "isAlfabank":"N",
    "cardNumber":"5154 **** 4025",
    "expirationDate":"07/15",
    "isDeletedCredit":"N",
    "lastTransactionDateForSender":"2015-12-15",
    "lastTransactionDateForRecipient":"2015-01-15",
    "paymentSystem":"MC",
    "accountBalance":"15250.50",
    "accountCurrency":"USD",
    "accountCurrenceName":"Доллар США",
    "bankId":"12345679",
    "bankNameLatin":"Sberbank",
    "bankNameCyrillic":"Сбербанк",
    "countryCode":"12",
    "bankColor":"#000008",
    }
  ]
}
----

* Получение параметров заданной карты

==== Пример запроса

*GET* /cards?id=1

==== Примеры ответа

----
{
  "humanId":""12345,
  "cardId":"1",
  "cardColor":"#000002",
  "cardName":"",
  "isSending":"Y",
  "isReception":"Y",
  "cardVerification":"S",
  "isDeletedDebit":"N",
  "isActive":"Y",
  "isAlfabank":"N",
  "cardNumber":"5154 **** 4025",
  "expirationDate":"07/15",
  "isDeletedCredit":"N",
  "lastTransactionDateForSender":"2015-12-15",
  "lastTransactionDateForRecipient":"2015-01-15",
  "paymentSystem":"MC",
  "accountBalance":"15250.50",
  "accountCurrency":"USD",
  "accountCurrenceName":"Доллар США",
  "bankId":"12345679",
  "bankNameLatin":"Sberbank",
  "bankNameCyrillic":"Сбербанк",
  "countryCode":"12",
  "bankColor":"#000008",
}
----

[[resources-card-create]]
=== Метод PUT

* Сохранение новой карты после совершения перевода

==== Пример запроса

*PUT* /cards/?id=1

==== Примеры ответа

----
{
  "humanId":""12345,
  "cardId":"1",
  "cardColor":"#000002",
  "cardName":"",
  "isSending":"Y",
  "isReception":"Y",
  "cardVerification":"S",
  "isDeletedDebit":"N",
  "isActive":"Y",
  "isAlfabank":"N",
  "cardNumber":"5154 **** 4025",
  "expirationDate":"07/15",
  "isDeletedCredit":"N",
  "lastTransactionDateForSender":"2015-12-15",
  "lastTransactionDateForRecipient":"2015-01-15",
  "paymentSystem":"MC",
  "accountBalance":"15250.50",
  "accountCurrency":"USD",
  "accountCurrenceName":"Доллар США",
  "bankId":"12345679",
  "bankNameLatin":"Sberbank",
  "bankNameCyrillic":"Сбербанк",
  "countryCode":"12",
  "bankColor":"#000008",
}
----

[[resources-card-update]]
=== Метод POST

* Сохранение даты последнего перевода

* Сохранение названия карты
