= REST Transactions
:toc: left
:source-highlighter: highlightjs


[[Overview]]
== Описание
Сервис предназначен для работы с объектом Transaction.

=== JSON schema

https://github.com/mbezrukov/alfa-p2p/blob/master/cards-json-schema[JSON schema] 

=== Параметры объекта Transaction
|===
| Параметр | Тип | Описание

| id
| String
| ID транзакции

| status
| String
| статус транзакции

| amount
| Long
| сумма транзакции

| fee
| Long
| сумма комиссии

| fullAmount
| Long
| сумма транзакции с комиссией

| date
| String
| Дата совершения транзакции (YYYYMMDDHHMMSSffffff)

| authorizationCode
| String
| Код авторизации в SV

| acsurl
| String
| URL страницы 3D Secure

3+| SenderCard

| card
| Object
| Информация по карте списания

| href
| String
| Строка запроса метода GET /cards/{cardsID} 

| number
| String
| Номер карты

| expirationYear
| Integer
| Год окончания срока действия

| expirationMonth
| Integer
| Месяц окончания срока действия

| cvv
| Integer
| CVV карты

3+| RecipientCard

| card
| Object
| Информация по карте зачисления

| href
| String
| Строка запроса метода GET /cards/{cardsID} 

| number
| String
| Номер карты

3+| Currency

| currency
| Object
| Информация по валюте основного счета

| href
| String
| Строка запроса метода GET /currencies

| code
| String
| Мнемоника валюты основного счета

| scale
| Integer
| Количество минорных единиц

3+| Authorization

| authorization
| Object
| Информация о 3ds-авторизации

| pareq
| String
| Запрос на аутентификацию отправителя

| md 
| String
| Контрольная сумма

| pares
| String
| Подтверждение авторизации карты

|===

=== Пример объекта
[source, json]
----
[
  {
    "id": "0000000000000001",
    "direction": "sender",
    "name": null,
    "alfabank": false,
    "number": "5154 **** 4025",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,
    "lastTransactionDate": "2015-12-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "1525050",
      "scale": "2",
      "currency": {
        "href": "http://.../currency/...",
        "code": "USD",
        "description": "Доллар США"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "id": "0000002",
      "name": "Сбербанк",
      "color": "#000008"
    }
  }
]
----

[[overview-http-verbs]]
== Список методов

|===
| Метод | Описание

| <<resources-cards-get, GET /cards>>
| Получение списка карт пользователя

| <<resources-cards-byCardId, GET /cards/{cardId}>>
| Получение информации о карте пользователя по ID

| <<resources-cards-patsh, PATCH /cards/{cardId}>>
| Редактирование параметров карты в системе

|===


[[resources-cards-get]]
=== Метод GET /cards

===== Параметры заголовков запросов
|===
| Параметр | Тип | Обязательность | По умолчанию | Описание 

| customerId
| String
| Mandatory
| ---
| Мнемоника пользователя и мнемоника местоположения

| applicationId
| String
| Mandatory
| ---
| ID приложения

| mode
| String
| Mandatory
| ---
| Режим работы ("all" - карты приложения + карты Альфа-Банка)

|===


===== Параметры строки запроса
|===
| Параметр | Тип | Обязательность | По умолчанию | Описание 

| verificationMethod
| String
| Optional
| "3DSecure"
| Статус верификации карты ("3DSecure", "hold", "notverify") +


| deleted
| Boolean
| Optional
| false
| Включать карты, удаленные пользователем? (true/false) +


| blocked
| Boolean
| Optional
| false
| Включать заблокированные карты? (true/false) +


| active
| Boolean
| Optional
| false
| Включать неактивные и просроченные карты? (true/false)

|===

==== Получение списка карт в поле карты списания
....
Дано:
  клиент находится на странице перевода.
Когда:
  клиент кликает в поле ввода карты списания.
Тогда:
  выпадает список карт: карты Альфа-Банка клиента (active = true и alfabank = true) и 
  те, с которых он ранее делал переводы (active = true и alfabank = false и direction = sender).
....
===== Example request

----
GET /cards/verificationMethod=3DSecure&deleted=false&blocked=false&active=true&direction=sender HTTP/1.1
Host: money.alfabank.ru 
Authorization:
Content-Type: 
Content-Length: 
customerId: AHQFFT
applicationId: ac-p2p
mode: all
----

===== Example response
[source, json]
----
HTTP/1.1 200 OK
[
  {
    "id": "0000000000000001",
    "direction": "sender",
    "name": null,
    "alfabank": true,
    "number": "5154 **** 4025",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,
    "lastTransactionDate": "2015-01-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "1525050",
      "scale": "2",
      "currency": {
        "href": "http://.../currency/...",
        "code": "RUR",
        "description": "Рубль"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "id": "0000001",
      "name": "Альфа-Банк",
      "color": "#000007"
    }
  },
  {
    "id": "0000000000000002",
    "direction": "sender",
    "name": null,
    "alfabank": false,
    "number": "5154 **** 4040",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,    
    "lastTransactionDate": "2015-01-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "25000",
      "scale": "2",
      "currency": {
        "href": "http://.../currency/...",
        "code": "RUR",
        "description": "Рубль"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "id": "0000002",
      "name": "Сбербанк",
      "color": "#000008"
    }
  }
]
----

==== Получение списка карт в поле карты зачисления
....
Дано:
  клиент находится на странице перевода.
Когда:
  клиент кликает в поле ввода карты зачисления.
Тогда:
  выпадает список карт: карты Альфа-Банка клиента (active = true и alfabank = true) и 
  те, на которые он ранее делал переводы (active = true и alfabank = false и direction = recipient).
....
===== Example request
----
GET /cards/allverificationMethod=3DSecure&deleted=false&blocked=false&active=true&direction=recipient HTTP/1.1
Host: money.alfabank.ru 
Authorization:
Content-Type: 
Content-Length: 
customerId: AHQFFT
applicationId: ac-p2p
mode: all
----
===== Example response
[source, json]
----
HTTP/1.1 200 OK
[
  {
    "id": "0000000000000003",
    "direction": "recipient",
    "name": null,
    "alfabank": true,
    "number": "5154 **** 4052",
    "expirationYear": "15",
    "expirationMonth": "07",
    "lastTransactionDate": "2015-01-15",
    "cvv": null,
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "100050",
      "scale": "2",
      "currency": {
        "href": "http://.../currency/...",
        "code": "RUR",
        "description": "Рубль"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "id": "0000001",
      "name": "Альфа-Банк",
      "color": "#000007"
    }
  },
  {
    "id": "0000000000000004",
    "direction": "recipient",
    "name": null,
    "alfabank": false,
    "number": "5154 **** 4070",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,
    "lastTransactionDate": "2015-01-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "5000050",
      "scale": "2",
      "currency": {
        "href": "http://.../currency/...",
        "code": "USD",
        "description": "Доллар США"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "id": "0000002",
      "name": "Сбербанк",
      "color": "#000008"
    }
  }
]
----

[[resources-cards-byCardId]]
=== Метод GET /cards/{cardId}


===== Параметры заголовков запросов
|===
| Параметр | Тип | Обязательность | По умолчанию | Описание 

| customerId
| String
| Mandatory
| ---
| Мнемоника пользователя и мнемоника местоположения


| applicationId
| String
| Mandatory
| ---
| ID приложения

|===


===== Параметры строки запроса
|===
| Параметр | Тип | Обязательность | По умолчанию | Описание 

| Id
| String
| Mandatory
| ---
| ID карты

|===


==== Получение параметров заданной карты 
....
Клиент получает все данные по своей карте (id = 0000000000000003)
....
===== Example request
----
GET /cards/0000000000000003 HTTP/1.1
Host: money.alfabank.ru 
Authorization:
Content-Type: 
Content-Length: 
customerId: AHQFFT
applicationId: ac-p2p
----
===== Example response
[source, json]
----
HTTP/1.1 200 OK
{
  "id": "0000000000000003",
  "direction": "recipient",
  "name": null,
  "alfabank": true,
  "number": "5154 **** 4052",
  "expirationYear": "15",
  "expirationMonth": "07",
  "cvv": null,
  "lastTransactionDate": "2015-01-15",
  "paymentSystem": "MC",
  "account": {
    "href": "http://.../accounts/...",
    "balance": "100050",
    "scale": "2",
    "currency": {
      "href": "http://.../currency/...",
      "id": "RUR",
      "description": "Рубль"
    }
  },
  "bank": {
    "href": "http://.../banks/...",
    "id": "0000001",
    "name": "Альфа-Банк",
    "color": "#000007"
  }
}
----


[[resources-cards-patch]]
=== Метод PATCH /cards/{cardId}

===== Параметры заголовков запросов
|===
| Параметр | Тип | Обязательность | По умолчанию | Описание 

| customerId
| String
| Mandatory
| ---
| Мнемоника пользователя и мнемоника местоположения


| applicationId
| String
| Mandatory
| ---
| ID приложения

|===


===== Параметры строки запроса
|===
| Параметр | Тип | Обязательность | По умолчанию | Описание 

| Id
| String
| Mandatory
| ---
| ID карты

|===


==== Редактирование названия карты
....
Дано:
  клиент кликает на псевдоссылку с названием карты.
Когда:
  вводит новое название карты (name = 0000000000000001)
Тогда:
  сохраняется новое название карты.
....
===== Example request
[source, json]
----
PATCH /cards/0000000000000001 HTTP/1.1
Host: money.alfabank.ru 
Authorization:
Content-Type: 
Content-Length: 
customerId: AHQFFT
applicationId: ac-p2p

{
  "name": "card1"
}
----
===== Example response
[source, json]
----
HTTP/1.1 200 OK
----
